mensagem: |
  §e§lTurkCraft
  §cServidor em manutenção.
  §cVolte em breve!
  §chttps://discord.gg/9Vx7BsqH para saber mais!
naotomakick: manu.nkick
adminperm: manu.admin
noperm: §cVocê não tem permissão para fazer isso!
joinms: 200